Repository Oe-In-DevelopTeam/TaskNavigator, pull requests merged in 2024-07, with the labels that each got.

#17 [2024/07/10] feature/login-page-ui >> 로그인 UI 구현
  src/main/resources/static/login.css
  src/main/resources/templates/login.html
Labels: 🌟 feature 🌟

#27 [2024/07/11] feature/main-page-ui >> 메인 페이지 구현
  src/main/resources/static/index.css
  src/main/resources/static/index.js
  src/main/resources/templates/index.html
Labels: 🌟 feature 🌟

#30 [2024/07/11] feature/create-card >> 카드 생성 기능 구현
  build.gradle
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/dto/CardRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/dto/CardResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardRepositoryCustom.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardRepositoryImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
Labels: 👾 bug 👾, 🌟 feature 🌟

#31 [2024/07/11] feat/admin/get-all-cards >> 관리자 카드 전체 조회 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
Labels: 🌟 feature 🌟

#32 [2024/07/11] feature/edit-card-content >> 카드 수정 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟

#33 [2024/07/11] feature/delete-card >> 카드 삭제 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
Labels: 🌟 feature 🌟

#34 [2024/07/10] feature/create-board-ui >> 보드 생성 페이지 UI
  src/main/resources/static/create-board.css
  src/main/resources/static/create-board.js
  src/main/resources/static/global.css
  src/main/resources/static/index.css
  src/main/resources/static/nav.css
  src/main/resources/templates/create-board.html
  src/main/resources/templates/index.html
Labels: 🌟 feature 🌟

#35 [2024/07/11] feature/get-card-detail >> 카드 상세 조회 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
Labels: 🌟 feature 🌟

#37 [2024/07/11] feature/card-detail-ui >> 카드 생성, 상세 페이지 UI
  src/main/resources/static/card-details.css
  src/main/resources/static/edit-card.css
  src/main/resources/templates/card-details.html
  src/main/resources/templates/create-board.html
  src/main/resources/templates/edit-card.html
  src/main/resources/templates/index.html
Labels: 🌟 feature 🌟

#41 ✨ update - #19 보드 목록 조회 기능 구현
  build.gradle
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/board/entity/QBoard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/board/entity/QUserBoardMatches.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/column/entity/QColumn.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUser.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUserRole.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUserRoleMatches.java
  src/main/generated/com/oeindevelopteam/tasknavigator/global/entity/QTimestamped.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/controller/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/BoardRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/BoardResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/entity/Board.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/entity/UserBoardMatches.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/BoardRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/BoardRepositoryCustom.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/BoardRepositoryImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepositoryCustom.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepositoryImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/column/entity/Column.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/User.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/repository/UserRoleMatchesRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/config/JpaConfiguration.java
Labels: 🌟 feature 🌟

#42 [2024/07/11] refactoring/card-status >> 카드와 카드태그 OneToMany 관계로 카드태그매칭 테이블에 관계 설정
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/CardCardTagPK.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/dto/CardRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/dto/CardResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/CardTag.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/CardTagMatches.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardTagRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/DataLoader.java
Labels: ♻️ refactoring ♻️

#43 [2024/07/11] feature/create-board >> 보드 생성 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/controller/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
Labels: 🌟 feature 🌟

#44 [2024/07/12] feature/login >> 로그인 기능 구현, 권한 부여 설정 및 UserRole 맵핑 설정 #3
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCardTag.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCardTagMatches.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUser.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUserRoleMatches.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/controller/UserController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/dto/UserSignupRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/User.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/UserRole.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/UserRoleMatches.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/repository/UserRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/security/UserDetailsImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/service/UserService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/config/SecurityConfig.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/security/JwtAuthenticationFilter.java
  src/main/resources/application.properties
Labels: 🌟 feature 🌟

#46 [2024/07/12] feature/update-board >> 보드 수정 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/controller/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/entity/Board.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟

#47 [2024/07/12] refactoring/column-to-section >> column을 section으로 변경
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/board/entity/QBoard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/section/entity/QSection.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/entity/Board.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepositoryImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/column/ColumnController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/ColumnController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
Labels: ♻️ refactoring ♻️

#48 ✨ update - #24 보드 삭제 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/controller/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
Labels: 🌟 feature 🌟

#49 [2024/07/12] feature/edit-card-status >> 카드 태그 수정 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/dto/CardTagEditRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/CardTag.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/CardTagMatches.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardTagRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟, ♻️ refactoring ♻️

#50 [2024/07/12] feature/create-column >> 컬럼 생성 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/ColumnController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/controller/SectionController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/dto/SectionRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/dto/SectionResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/SectionStatus.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/repository/SectionRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/repository/SectionStatusRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/service/SectionService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟

#51 [2024/07/10] feature/delete-column >> 컬럼 삭제 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/controller/SectionController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/SectionStatus.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/repository/SectionStatusRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/service/SectionService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟

#52 [2024/07/12] feature/move-column >> 컬럼 이동 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/controller/SectionController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/service/SectionService.java
Labels: 🌟 feature 🌟

#57 [2024/07/12] feature/board >> 보드 목록 조회 기능 오류 수정, DTO타입으로 반환
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/controller/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/BoardListResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/CardDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/SectionDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/entity/Board.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepositoryCustom.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepositoryImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
Labels: 👾 bug 👾, 🌟 feature 🌟

#58 [2024/07/12] refactoring/connect-front >> 프론트 url로 들어갈 수 있도록 변경
  src/main/java/com/oeindevelopteam/tasknavigator/domain/home/controller/HomeController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/controller/UserController.java
  src/main/resources/static/css/nav.css
  src/main/resources/templates/card-details.html
  src/main/resources/templates/create-board.html
  src/main/resources/templates/edit-card.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: ♻️ refactoring ♻️

#60 [2024/07/13] refactoring/user >> 유저 관련 refactoring, bug fix
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/board/entity/QBoard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/board/entity/QUserBoardMatches.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCard.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCardTag.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/card/entity/QCardTagMatches.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/section/entity/QSection.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/section/entity/QSectionStatus.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUser.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUserRole.java
  src/main/generated/com/oeindevelopteam/tasknavigator/domain/user/entity/QUserRoleMatches.java
  src/main/generated/com/oeindevelopteam/tasknavigator/global/entity/QTimestamped.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/User.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/UserRole.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/repository/UserRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/security/UserDetailsServiceImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/service/UserService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
  src/main/resources/application.properties
Labels: 👾 bug 👾, ♻️ refactoring ♻️

#64 [2024/07/13] feature/connect-front-back-login >> 로그인과 회원가입 페이지와 백엔드 연결
  src/main/java/com/oeindevelopteam/tasknavigator/global/security/JwtAuthenticationFilter.java
  src/main/resources/static/js/login.js
  src/main/resources/static/js/signup.js
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: 🙋🏻‍♂️ help 🙋🏻‍♂️, 🌟 feature 🌟

#66 [2024/07/14] feature/add-errorcode 에러코드 추가
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟, ♻️ refactoring ♻️

#68 [2024/07/14] feature/front-dragdrop >> Drag & Drop 기능 구현
  src/main/resources/static/css/index.css
  src/main/resources/static/js/create-board.js
  src/main/resources/static/js/drag-drop.js
  src/main/resources/static/js/index.js
  src/main/resources/templates/index.html
Labels: 🌟 feature 🌟

#69 [2024/07/14] feature/get-cards >> 유저 초대받은 보드 카드 전체 조회, 태그별 조회, 담당자별 조회 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/TaskNavigatorApplication.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/entity/UserBoardMatches.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/dto/CardResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/repository/CardRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟, ♻️ refactoring ♻️

#77 [2024/07/15] feature/search-card-ui >> 카드 조회 UI 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/home/controller/HomeController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
  src/main/resources/static/css/create-board.css
  src/main/resources/templates/cards.html
  src/main/resources/templates/index.html
Labels: 🌟 feature 🌟

#78 [2024/07/15] feature/set-card-permissions >> 모든 카드 기능 분기처리, role 구분 처리
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟, ♻️ refactoring ♻️

#79 [2024/07/15] feature/create-comment >> 댓글 작성 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/controller/CardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/entity/Card.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/card/service/CardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/Controller/CommentController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/entity/Comment.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/service/CommentService.java
Labels: 🌟 feature 🌟, ♻️ refactoring ♻️

#80 [2024/07/15] feature/get-comments >> 댓글 조회 기능 구현
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/CommentController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/Controller/CommentController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/repository/CommentRepository.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/comment/service/CommentService.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/exception/ErrorCode.java
Labels: 🌟 feature 🌟

#81 [2024/07/16] feature/connect-board-ui >> 메인 페이지와 프론트 연결
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/controller/BoardController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/BoardListResponseDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/CardDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/dto/SectionDto.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/repository/UserBoardMatchesRepositoryImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/home/controller/HomeController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/controller/UserController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/dto/UserInfoDto.java
  src/main/resources/static/css/global.css
  src/main/resources/static/css/index.css
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/create-board.js
  src/main/resources/static/js/index.js
  src/main/resources/static/js/login.js
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
Labels: 🌟 feature 🌟

#83 [2024/07/16] feature/connect-board-ui >> drag & drop 기능 수정
  src/main/java/com/oeindevelopteam/tasknavigator/domain/board/service/BoardService.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/home/controller/HomeController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/controller/SectionController.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/entity/Section.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/section/service/SectionService.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/entity/User.java
  src/main/java/com/oeindevelopteam/tasknavigator/domain/user/security/UserDetailsServiceImpl.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/config/SecurityConfig.java
  src/main/java/com/oeindevelopteam/tasknavigator/global/config/WebConfig.java
  src/main/resources/static/css/global.css
  src/main/resources/static/js/basic.js
  src/main/resources/static/js/drag-drop.js
  src/main/resources/templates/index.html
Labels: 🌟 feature 🌟
